create table if not exists game_result (
    id integer primary key generated by default as identity,
    player_north_name varchar not null,
    player_south_name varchar not null,
    outcome varchar not null,
    winner_name varchar,
    deadwood_value smallint not null,
    winner_score smallint,
    created_at timestamp not null
);

create index on game_result(created_at);
