[tool.poetry]
name = "gin-scoring-fastapi-version"
version = "0.1.0"
description = ""
authors = ["Olivier Philippon <olivier@dunsap.com>"]
license = "MIT"
packages = [
    { include = "gin_scoring", from = "./src" },
]

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.110.2"
uvicorn = {extras = ["standard"], version = "^0.29.0"}
sqlalchemy = "^2.0.29"
alembic = "^1.13.1"
sqladmin = "^0.16.1"
pydantic-settings = "^2.2.1"


[tool.poetry.group.dev.dependencies]
ruff = "^0.4.2"
black = "^24.4.2"
pre-commit = "^3.7.0"
mypy = "^1.10.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
