# Generated by Django 5.1.1 on 2026-08-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scoreboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameresult",
            name="double_score",
            field=models.BooleanField(default=False),
        ),
    ]
