import type { GetServerSideProps } from 'next'

import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import {pool} from "../db";

type HomeProps = {
  nowFromPostgres: number
}

export default function Home(props: HomeProps) {
  console.log('props=', props)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          According to Postgres the current time is{' '}
          <code className={styles.code}>{
            new Intl.DateTimeFormat(undefined, {dateStyle: 'long', timeStyle: 'medium'}).format(new Date(props.nowFromPostgres))
          }</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}


export const getServerSideProps: GetServerSideProps = async (context) => {
  const { rows }= await pool.query('select now()')
  const nowFromPostgres:Date = rows[0].now
  console.debug(' nowFromPostgres=',  nowFromPostgres)
  return {
    props: {nowFromPostgres: nowFromPostgres.getTime()}, // will be passed to the page component as props
  }
}
