# Generated by Django 5.1.1 on 2024-10-06 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerPair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_1_name", models.CharField(max_length=50)),
                ("player_2_name", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GameResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "outcome",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "draw"),
                            (1, "knock"),
                            (2, "undercut"),
                            (3, "gin"),
                            (4, "big_gin"),
                        ]
                    ),
                ),
                (
                    "winner",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Player 1"), (2, "Player 2")], null=True
                    ),
                ),
                ("deadwood_value", models.PositiveSmallIntegerField(null=True)),
                ("winner_score", models.PositiveSmallIntegerField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "player_pair",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scoreboard.playerpair",
                    ),
                ),
            ],
        ),
    ]
